// <auto-generated />
using System;
using System.Collections.Generic;
using BookingModule.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookingModule.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    [Migration("20260227135703_BookingModuleMigration")]
    partial class BookingModuleMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookingModule.Models.BookingModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("cancellation_reason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("cancelled_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("check_in")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("check_out")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("guest_email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("guest_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("guest_phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("payment_method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("payment_reservation_id")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("room_id")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("saga_id")
                        .HasColumnType("uuid");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("total_price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("saga_id")
                        .IsUnique();

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BookingModule.Models.ProcessedCommandsModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("command_id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("command_type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("error_message")
                        .HasColumnType("text");

                    b.Property<DateTime>("processed_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Dictionary<string, object>>("result_payload")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("saga_id")
                        .HasColumnType("uuid");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.HasIndex("saga_id")
                        .IsUnique();

                    b.ToTable("ProcessedCommands");
                });

            modelBuilder.Entity("BookingModule.Models.SagaEventLogsModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("correlation_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("event_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("event_type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("occurred_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Dictionary<string, object>>("payload")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("processed_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("saga_id")
                        .HasColumnType("uuid");

                    b.Property<string>("source_module")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("saga_id")
                        .IsUnique();

                    b.ToTable("SagaEventLogs");
                });

            modelBuilder.Entity("BookingModule.Models.SagaStatesModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("completed_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("current_step")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("error_code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("error_message")
                        .HasColumnType("text");

                    b.Property<DateTime>("last_updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("max_retries")
                        .HasColumnType("integer");

                    b.Property<Dictionary<string, object>>("metadata")
                        .HasColumnType("jsonb");

                    b.Property<int>("retry_count")
                        .HasColumnType("integer");

                    b.Property<Guid>("saga_id")
                        .HasColumnType("uuid");

                    b.Property<string>("saga_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("started_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.HasIndex("saga_id")
                        .IsUnique();

                    b.ToTable("SagaStates");
                });

            modelBuilder.Entity("BookingModule.Models.SagaStepsModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("compensated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("completed_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("error_code")
                        .HasColumnType("text");

                    b.Property<string>("error_message")
                        .HasColumnType("text");

                    b.Property<bool>("is_compensated")
                        .HasColumnType("boolean");

                    b.Property<Dictionary<string, object>>("request_payload")
                        .HasColumnType("jsonb");

                    b.Property<Dictionary<string, object>>("responce_payload")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("saga_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("started_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("step_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("step_order")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("saga_id")
                        .IsUnique();

                    b.ToTable("SagaSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
