// <auto-generated />
using System;
using System.Collections.Generic;
using InventoryModule.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InventoryModule.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260227172346_InventoryModuleMigration")]
    partial class InventoryModuleMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InventoryModule.Models.RoomAvailability", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_available")
                        .HasColumnType("boolean");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("price_multiplier")
                        .HasColumnType("numeric");

                    b.Property<string>("room_id")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("RoomAvailabilities");
                });

            modelBuilder.Entity("InventoryModule.Models.RoomModel", b =>
                {
                    b.Property<string>("id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Dictionary<string, object>>("amenities")
                        .HasColumnType("jsonb");

                    b.Property<int>("capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<int?>("floor")
                        .HasColumnType("integer");

                    b.Property<decimal>("price_per_night")
                        .HasColumnType("numeric");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("InventoryModule.Models.RoomReservationModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("booking_id")
                        .HasColumnType("uuid");

                    b.Property<string>("cancellation_reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("cancelled_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("check_in")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("check_out")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("guest_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Dictionary<string, object>>("metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("reservation_reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("room_id")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("saga_id")
                        .HasColumnType("uuid");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.ToTable("RoomReservations");
                });
#pragma warning restore 612, 618
        }
    }
}
